### ISSUE TITLE
Make the logger look/act more like a logger

### ISSUE THREAD

**Issue by davehunt** [mozilla/mciconf#17]
At the moment the logger seems to be a mix of log messages and alerts. Could we make this a simple logger with various log levels? Rather than having alerts disappear after some time with a show all button, they can just be scrolled to. It will also keep all log entries in sequence which doesn't currently seem to be the case.

Here's a mockup of how it might look:
![screen shot 2014-02-25 at 2 53 08 pm](https://f.cloud.github.com/assets/122800/2258764/206fcb08-9e2d-11e3-85e4-214f25f04cff.png)

We could then perhaps add a DEBUG level, and a checkbox to show these entries.

**Comment by whimboo** [comment]
No further work will happen on this repository.
