### ISSUE TITLE
adding the new Balrog (aus4.mozilla.org) channel names

### ISSUE THREAD

**Issue by kjozwiak** [mozilla/mciconf#37]
mciconf is still listing the old channel names rather than the new ones from the balrog server:

* "esrtest" should be listed as --> "esr-localtest"
* "releasetest" should be listed as --> "esr-cdntest"

The last channel which is "esr" stays the same from the looks of 
* https://wiki.mozilla.org/Releases/Update_Channels

**Comment by lizzard** [comment]
Looks good to me!

**Comment by whimboo** [comment]
PR #38 has been merged, and staging is updated: http://mozilla.github.io/mciconf/app/
